package ar.edu.unq.integrador.concepto;

public enum Concepto {
	VINCHUCA_INFESTANS,
	VINCHUCA_SORDIDA,
	VINCHUCA_GUASAYANA,
	CHINCHE_FOLIADA,
	PHTIA_CHINCHE,
	NINGUNA,
	IMAGEN_POCO_CLARA,
	NO_DEFINIDO
}
